/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=WorkerBindings` (hash: 781a87019ff73bad5e2df650f820a5e5)
interface __BaseEnv_WorkerBindings {
	Sandbox: DurableObjectNamespace<import("./src/index").Sandbox>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "Sandbox";
	}
	interface Env extends __BaseEnv_WorkerBindings {}
}
interface WorkerBindings extends __BaseEnv_WorkerBindings {}
